### ISSUE TITLE
Usage of newest version

### ISSUE THREAD

**Issue by Hirzelts** [socialsoftware/mono2micro#67]
Hello,

I am a software engineering Master student and currently working on a research project which concerns itself with investigating tool support for Monolith to Microservice migration.

Currently I am trying to understand the input needed for the newest version. In particular the nature of the files for the Accesses Collector to work:

![grafik](https://user-images.githubusercontent.com/18172141/188601277-24532858-cac4-4803-aa9a-8d224bbc445f.png)

Unfortunately I could not find documentation about what an "Accesses File" or an "IDToEntity File" is and how they are generated.

I propose to add usage documentation for the newest version to the repo.

If I missed this documentation I apologize and ask you to please share a link to it.

**Comment by ritosilva** [comment]
Hello,

Thanks for you interest!

Concerning the sources, you can find them here, https://github.com/socialsoftware/mono2micro/blob/master/collectors/spoon-callgraph/data/collection/staticCollectionDatafiles.zip ,for several codebases.
Of course, you can also use the spon collector to generate them, which is here, https://github.com/socialsoftware/mono2micro/tree/master/collectors/spoon-callgraph

Actually, we are in the process of refactoring and extending the tool and the working version is here, https://github.com/socialsoftware/mono2micro/tree/mono-micro-redesign-unstable

BTW, we are in the process of assessing the tool after the refactoring, which will be done in the next month. Please, let me know if you are interested, or know people that can in interested, in participating. Thanks!

**Comment by ritosilva** [comment]
Hello, the UI was redesigned. We hope that it is more clear now.
