### ISSUE TITLE
Usage of spoon Collector 

### ISSUE THREAD

**Issue by Hirzelts** [socialsoftware/mono2micro#70]
Hello,

I am currently trying to use spoon collector on several codebases.

All Codebases I tried so far make the programm error out or lead to empty json files.

I would like to ask, where I can find some of the codebases you collected the Accesses files and IDToEntity files from in https://github.com/socialsoftware/mono2micro/blob/master/collectors/spoon-callgraph/data/collection/staticCollectionDatafiles.zip.

Thank You.

**Comment by ritosilva** [comment]
Hello,

In the article, https://doi.org/10.13052/jwe1540-9589.2158, you can find the info.
Anyway, we have stored a copy of each code base in google drive, https://drive.google.com/drive/folders/1QiAPyM4ezhihoqJdSEJNmwfNDNzzsYv1?usp=share_link

BTW, in master branch you will find the most recent version of mono2micro, now extended to also accept git logs to generate decompositions and a git collector (unpublished research, but you can see the README.md where it explains how to use it).

Thanks for your interest!

Best regards.

**Comment by Hirzelts** [comment]
I like to ask a question about the git collector:

Am i right to assume, that the git collector only works if the spoon collector generated sensible files beforehand, which means the git collector cannot collect independently of the spoon collector for a codebase?

That is what i gather from this part of the readme: "_Finally, the scripts assume that for each codebase in resources/codebases.csv, there is a folder with the codebase name under resources/codebases_collection with 3 files: the static analysis data file, the id to entity file, and the entity to id file._"

Best regards.

**Comment by ritosilva** [comment]
Yes, you are correct.
Actually, it would be enough to provide the information about which files
correspond to domain entities, but, in the research done when
developing the git collector, we also wanted to compare the results
obtained using the metrics for cohesion, coupling, etc, which requires the
sequences of accesses.
______
António Rito Silva
Associate Professor, Instituto Superior Técnico, University of Lisbon
Distributed Parallel and Secure Systems, INESC-ID
Rua Alves Redol, 9, Room 535
1000-029 Lisboa, Portugal
Tel.: +351-213 100 263

**Comment by ritosilva** [comment]
We have change it. It does not require the use of Spoon for the commits log. 
You only have to prepare an Id2Entity json file with the list of the domain entities.

**Comment by Hirzelts** [comment]
Great! Does this mean Mono2Micro can be applied to every Github project, when using the commit-collector?

**Comment by ritosilva** [comment]
Yes, the only thing you need to do is to create the Id2Entity json file "by
hand" containing the names of the classes that are the entities of the
repository.
______
António Rito Silva
Associate Professor, Instituto Superior Técnico, University of Lisbon
Distributed Parallel and Secure Systems, INESC-ID
Rua Alves Redol, 9, Room 535
1000-029 Lisboa, Portugal
Tel.: +351-213 100 263
